converters/urls.py
from django.contrib import admin
from django.urls import path
from converters import views

urlpatterns = [
    path('convert/', views.convert, name='convert')
]

testdep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weather/', include('weather.urls')),
    path('converters/', include('converters.urls'))
]

weather/urls.py
from django.contrib import admin
from django.urls import path
from weather import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('current/', views.main, name='weather'),
    path('example/<name>/', views.example)
]

converters/models.py
from django.db import models

# Create your models here.

weather/models.py
from django.db import models

# Create your models here.

converters/forms.py
from django import forms
from django.core.exceptions import ValidationError

class ConverterForm(forms.Form):
    temperature = forms.FloatField(label='Temperatura', max_value=100.0, min_value=1.0)

    def clean_temperature(self):
        #print("CCC")
        #print(self.cleaned_data)
        temperature = self.cleaned_data['temperature']
        if temperature:
            temp = float(temperature)
            if temp < 10.0:
                raise ValidationError("Temperatura musi byc większa niż 10.0")

converters/views.py
from django.shortcuts import render

from converters import forms

def convert(request):
    temp = 0
    form = forms.ConverterForm()

    if request.method == 'POST':
        form = forms.ConverterForm(request.POST)
        if form.is_valid():
            temp = request.POST['temperature']
        else:
            print(form.errors)
    else:
        form = forms.ConverterForm()

    context = {'form': form, 'temp': temp}
    return render(request, "converters/main.html", context)

weather/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render

import datetime

def main(request):
    temp = get_temp()

    context = {
        'name': 442,
        'temperature': temp,
        'is_user': is_user(),
        'calc': calculate(),
        'today': datetime.date.today()
    }
    return render(request, "weather/main.html", context)


def get_temp():
    return 2.0

def example(request, name):
    print(name, type(name))
    name += "LOL"
    return render(request, "weather/other.html", {'name': name})

def is_user():
    return True

def calculate():
    return {'item1': 1, 'item2': 2, 'item3': 3, 'item4': 4}

converters/templates/converters/main.html
{% extends 'base.html' %}

{% block title %}
    <title>Moje konwertery</title>
{% endblock %}

{% block header %}
<div class="card text-white bg-dark">
    <div class="card-body">
      MOJE KONWERTERY
    </div>
  </div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div>
        Wpisano: {{ temp }}
    </div>
        <div class="col-md-3">
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field, error in form.errors.items %}
                {{ error }}
                {% endfor %}
              </div>
            {% endif %}
            <form action="/converters/convert/" method="POST" class="mt-3">
                {% csrf_token %}

                <label for="id_temperature" class="form-label">Podaj wartość temperatury w Celsjuszach</label>
                <input type="number" name="temperature" class="form-control mb-3" id="id_temperature" max=100 min=1>

                <button type="submit" class="btn btn-dark">Przelicz</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

weather/templates/base.html
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% block title %}
    <title>Moja strona</title>
{% endblock %}
 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
       crossorigin=""/>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>

<body>
    <div class="container">
    <header>
        {% include 'nav.html' %}
        {% block header %}
        {% endblock %}
    </header>
        {% block content %}

        {% endblock %}
    <footer>

    </footer>
    </div>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
     <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
               crossorigin=""></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
     {% block scripts %}
     {% endblock %}
 </body>
</html>

weather/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Moja strona</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'weather' %}">Pogoda</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'convert' %}">Konwertery</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

weather/templates/weather/main.html
{% extends 'base.html' %}

{% load weather_filters %}
{% load weather_tags %}
{% load widgets %}

{% block content %}
<h1>POGODA</h1>

{% weather_widget 2 %}

<p>Hello, {{ name|reverse }}</p>
<p>Temperature is {{ temperature }}</p>

{% create_date today %}

{% add_number 1.1 2.2 %}

<p>
{% lorem 4 p %}
</p>
 <div id="map"></div>

 {% if is_user and name == "Adam" %}
    <p>Jestes userem Adam</p>
 {% else %}
 <p>Nie jestes userem</p>
 {% endif %}

 {% with calculated=calc %}
    {% for key, value in calculated.items %}
    <div class="{% cycle "bolded" "" %}">{{ key }}, {{ value }}</div>
    {% empty %}
    Nie ma liczb
    {% endfor %}
 {% endwith %}

{% endblock %}

{% block stopka %}
to jest stopka

{% include 'weather/main2.html' %}
{% endblock %}

{% block scripts %}
    <script>
        var map = L.map('map', {
                center: [51.505, -0.09],
                zoom: 13
        });
    </script>
{% endblock %}

weather/templates/weather/main2.html
<h2>Inna tresc</h2>

weather/templates/weather/other.html
iiiiii

{{ name }}
{% now "jS F Y H:i" %}

{% lorem 3 p %}

It is {% now "SHORT_DATETIME_FORMAT" %}

weather/templates/weather/weather_widget.html
<div style="padding: 20px; border: 5px solid black; width: 350px;">
    <p style="text-align: center;">AKTUALNA POGODA W {{ cities.city|upper }}</p>
</div>